services:
  - type: web
    name: twitter-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TWITTER_AUTH_TOKEN
        sync: false
      - key: TWITTER_CT0
        sync: false
    healthCheckPath: /api/v1/health